/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AUTH_GITHUB_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GITHUB_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GOOGLE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GOOGLE_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GROQ_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "abay": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "artifacts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "chats": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}